[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "audembed"
version = "0.1.0"
dependencies = [
    "matplotlib",
    "torch",
    "einops",
    "mirdata",
    "numpy",
    "datasets",
    "librosa",
    "soundfile",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["audembed*"]